apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carts-db-sockshop2-staging-destination
spec:
  host: carts-db.sockshop2-staging.svc.cluster.local
  subsets:
  - name: blue
    labels:
      deployment: carts-db-blue
  - name: green
    labels:
      deployment: carts-db-green